export const STATUS_ACCEPTED = "ACCEPTED";
export const STATUS_NOT_ACCEPTED = "NOT_ACCEPTED";
export const STATUS_WAITING = "WAITING";
export const STATUS_VALIDATED = "VALIDATED";
export const STATUS_COMPLETED = "COMPLETED";
